name: pytorchGeo

############################################################################################################## 
# This is a "yml" file for setting up a python environment for geoscience machine learning 
# using pytorch and other useful libraries.

# The environment is named "pytorchGeo".

# This makes use of "mamba," a Python-based CLI conceived as a drop-in replacement for conda 
# as was originally used in the "anaconda" python distribution. 
# For details see: "https://mamba.readthedocs.io/en/latest/installation/mamba-installation.html".

# For the latest information about installing pytorch
# see: https://pytorch.org/get-started/locally/.

# To install the environment perform two steps: first make a barebones jupyterlab environment, 
# then update it with this yml file.

# From the command line in a terminal as an ordinary user with a prompt '$' do the following
# (choosing the default answers to questions):

# wget "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
# bash Miniforge3-$(uname)-$(uname -m).sh

# $ mamba create -n pytorchGeo jupyterlab -c conda-forge
# close the terminal and open a new one ... then go to folder with the yml file

# $ cd pythonEnvironments/Mamba/pyTorch/
# $ mamba env update --name pytorchGeo --file environment-pytorchGeo.yml
  
### Warning: don't use the flag "--prune" above as it will remove jupyterlab, etc! ###
  
### You can now start the environment by typing:
  
# $ mamba activate pytorchGeo
############################################################################################################## 

channels: 
  - conda-forge
  - pytorch
  - nvidia
  - gpytorch
  # - fastchan

dependencies:
  - python
  - numpy
  - scipy
  - scikit-learn
  - scikit-image
  - h5py
  # - jupyter ### jupyter notebook only
  # - jupyterlab ### seems this might cause trouble when updating
  - jupytext
  - ipywidgets
  - ipykernel
  - ipympl
  - pandas
  - matplotlib
  - seaborn
  - pillow
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8
#
  - pyarrow
#
  - bokeh
#
  - umap-learn
  - susi
#  - somoclu
#
  - captum
#  - tqdm
  # - arrow
#
  - gdal
  - rasterio
#
  - opencv
  - pywavelets
  - pycwt
#
  - librosa
#
  - cython
  - pyproj
  - shapely
  - rtree
  - pyorbital
#
  - sympy
#
  - astropy
#
  - tabulate
#
  - gpytorch
  # - gpy
  # - botorch
  # - fastai
#
  - opentsne
#
  - tslearn
  - dtaidistance
#
  - natsort
#
  - pip
  - pip:
    - pyro-ppl
    - SALib    
    - tables
    - torch-summary
    - kornia
    - imgaug
    - pygeotools
    - pygeoprocessing
    - pyrtools
    - earthpy
    - filterpy
    - acoustics
    - deap
    - arviz
    - desolver
    - colormaps
    - ncps
    - pytorch-lightning
#
    - vscode-tqdm
     
#    - emukit
#    - minisom
#    - quicksom
#    - simpsom
  
